staging:
  type: deploy
  environment: staging
  script:
  - apt-get update -qy
  - apt-get install -y
  - gem install dpl
  - dpl --provider=heroku --app=$HERUKU_NAMEAPP --api-key=$HEROKU_APIKEY
  only:
  - master
