version:  '3'
services:
  app:
    container_name: InTraining-php
    build: .
    ports:
    - "80:80"
    volumes:
    - ./:/var/www/html/
    depends_on:
      - mysql
      - phpmyadmin
    links:
      - mysql
  mysql:
    container_name: InTraining-mysql
    image: mysql:5
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
    volumes:
    - ./:/var/lib/mysql
  phpmyadmin:
    container_name: InTraining-phpMyAdmin
    image: phpmyadmin/phpmyadmin
    links:
    - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
    - '8080:80'